# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: testvmss

variables: 
- name: 'clustername' # new variable defined in YAML
  value: 'akscni-cluster'
- name: 'rgname' # new variable defined in YAML
  value: 'akscni-rg'

steps:
# Specify python version
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    architecture: 'x64'

# Update to latest Azure CLI version
- bash: pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge
  displayName: 'Upgrade Azure CLI'

# kubeconfig
- task: AzureCLI@2
  inputs:
    azureSubscription: 'akspolicy-rg-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials -g $(rgname) --cluster-name $(clustername)
      sudo az aks install-cli
      kubectl get node
    failOnStandardError: true
