# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: testvmss

variables: 
- name: 'clustername' # new variable defined in YAML
  value: 'akscni-cluster'
- name: 'rgname' # new variable defined in YAML
  value: 'akscni-rg'

steps:
- task: AzureCLI@2s
  inputs:
    azureSubscription: 'akspolicy-rg-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      az aks get-credentials -g $(rgname) -n $(clustername)
      sudo az aks install-cli
      kubectl get node
    failOnStandardError: true
