# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# resources:
#   repositories:
#   - repository: sampleapp
#     type: git
#     endpoint: JacobBaekHome
#     name: JacobBaekHome/sampleapp

jobs:
variables: 
- name: 'clustername' # new variable defined in YAML
  value: 'akscni-cluster'
- name: 'rgname' # new variable defined in YAML
  value: 'akscni-rg'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'akspolicy-rg-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials -g $(rgname) --cluster-name $(clustername)
      sudo az aks install-cli
      kubectl get node
    failOnStandardError: true
