# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: testvmss

variables: 
- name: 'clustername' # new variable defined in YAML
  value: 'akscni-cluster'
- name: 'rgname' # new variable defined in YAML
  value: 'akscni-rg'

# https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'akscni-rg-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      echo "[info] print aks list"
      az aks list
      echo "[info] get credentials"
      az aks get-credentials -g $(rgname) -n $(clustername)
      echo "[info] install kubectl"
      sudo az aks install-cli
      echo "[info] get the result using kubectl"
      kubectl get node
      echo "[info] succeed"
    failOnStandardError: true