# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables: 
- name: 'clustername' # new variable defined in YAML
  value: 'akstest-cluster'
- name: 'rgname' # new variable defined in YAML
  value: 'akstest-rg'

schedules:
- cron: '11 45 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - main

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'akstest-rg-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      echo "[info] get credentials"
      az aks update -g $(rgname) -n $(clustername) --update-cluster-autoscaler --min-count 2 --max-count 3
      echo $?
      echo "[info] succeed"
    failOnStandardError: false
