# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: testvmss

variables: 
- name: 'clustername' # new variable defined in YAML
  value: 'akstest-cluster'
- name: 'rgname' # new variable defined in YAML
  value: 'akstest-rg'

schedules:
- cron: '11 00 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - *

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'akscni-rg-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      echo "[info] get credentials"
      az aks update -g $(rgname) -n $(clustername) --enable-cluster-autoscaler --min-count 1 --max-count 3
      echo $?
      echo "[info] succeed"
    failOnStandardError: false
